use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewResponse {
    pub total: i64,
    pub page: i64,
    #[serde(rename = "pageSize")]
    pub page_size: i64,
    #[serde(rename = "totalPages")]
    pub total_pages: i64,
    pub campuses: Vec<Campus>,
    #[serde(rename = "activeCampus")]
    pub active_campus: Option<serde_json::Value>,
    pub data: Vec<ReviewItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Campus {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewItem {
    pub id: i64,
    pub user_id: i64,
    pub school_id: i64,
    // 保留新版字段
    pub status: String,
    pub reject_reason: Option<serde_json::Value>,
    pub content: String,
    pub images: Option<serde_json::Value>,
    pub display_name: String,
    pub created_at: String,
    pub updated_at: String,
    pub view_count: i64,
    pub submission_id: Option<serde_json::Value>,
    pub mod_task_id: String,
    pub mod_suggestion: String,
    pub campus_id: Option<serde_json::Value>,
    pub like_count: i64,
    pub reply_count: i64,
    pub review_weight: f64,
    pub nickname: String,
    pub verified_school_id: Option<serde_json::Value>,
    pub avatar_path: Option<serde_json::Value>,
    pub level: Option<serde_json::Value>,
    pub title: Option<serde_json::Value>,
    pub campus_name: Option<String>,
    #[serde(rename = "isAnonymous")]
    pub is_anonymous: bool,
    #[serde(rename = "isVerified")]
    pub is_verified: bool,
    pub user_liked: bool,
    pub rating: Option<Rating>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Rating {
    pub id: i64,
    pub review_id: i64,
    pub dormitory: Option<i64>,
    pub cafeteria: Option<i64>,
    pub faculty: Option<i64>,
    pub environment: Option<i64>,
    pub culture: Option<i64>,
    pub employment: Option<i64>,
    pub safety: Option<i64>,
}

#[cfg(test)]
mod tests {
    use crate::legacy_api::school_comments::ReviewResponse;

    #[test]
    fn test_reply_deserde() {
        let json = r#"{
    "total": 14,
    "page": 1,
    "pageSize": 10,
    "totalPages": 2,
    "campuses": [
        {
            "id": 1131,
            "name": "东校区"
        },
        {
            "id": 1132,
            "name": "师范分院校区"
        },
        {
            "id": 1133,
            "name": "南校区"
        },
        {
            "id": 1134,
            "name": "北校区"
        }
    ],
    "activeCampus": null,
    "data": [
        {
            "id": 2114,
            "user_id": 3275,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "此城市一个月有半个月中度污染及以上，空气质量及其差劲，北校每天早上七点多得出去跑操，晚上还有晚自习，宿舍楼堪比德军战俘营，宿舍厕所每天看了都只能说人类拉了一地，小便冲大便，澡堂子水都是偏黄的，还没有吹风机，拖鞋是从来不消毒的，一箱子拖鞋堪比生化武器，尤其理工科排课更是史中之史，每周四天早八三天满课，每周都有几天有莫名其妙活动占用为数不多的午休，强制学生参加某些无意义活动，教学楼实验器材比我岁数都大，都得是上个世纪的了，学校教室凳子桌子斑驳不堪不知道以为送到二战战场上经过炮火的洗礼了，最主要一栋楼上机课爬十一楼电梯就俩，每周都得上下一次十一楼，不知道以为搁这做有氧呢，这边也是给到拉完了",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-04-22 09:20:50",
            "updated_at": "2026-04-22 09:20:50",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "51ce1ab5-f3f0-4f65-b247-fcae3b335f22",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 4,
            "reply_count": 2,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户3",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        },
        {
            "id": 2113,
            "user_id": 3275,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "此城市一个月有半个月中度污染及以上，空气质量及其差劲，北校每天早上七点多得出去跑操，晚上还有晚自习，宿舍楼堪比德军战俘营，宿舍厕所每天看了都只能说人类拉了一地，小便冲大便，澡堂子水都是偏黄的，还没有吹风机，拖鞋是从来不消毒的，一箱子拖鞋堪比生化武器，尤其理工科排课更是史中之史，每周四天早八三天满课，每周都有几天有莫名其妙活动占用为数不多的午休，强制学生参加某些无意义活动，教学楼实验器材比我岁数都大，都得是上个世纪的了，学校教室凳子桌子斑驳不堪不知道以为送到二战战场上经过炮火的洗礼了，最主要一栋楼上机课爬十一楼电梯就俩，每周都得上下一次十一楼，不知道以为搁这做有氧呢，这边也是给到拉完了",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-04-22 09:20:21",
            "updated_at": "2026-04-22 09:20:21",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "3b60ca37-2a66-49a1-b35f-dc834dafea7a",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 3,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户3",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        },
        {
            "id": 4367,
            "user_id": 8655,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "我仅代表我个人体验观点，当然了，不同校区不同院肯定是有差距的，我们部分季节有早操，但是吧…你要是有什么情况都可以请假嘛，仅仅大一有点晚自习，上课老师绝对绝对负责，奈何我们很多学生学习确实不太认真，食堂我真的没的说，真的挺不错了，一点不比外面差，你去网上都能搜到，宿舍是25年暑假翻新，我的情况是大一8人寝，大二部分4人，大三大四都4人，环境就跟另一个评论照片一样，还有今年暑假又要翻新，具体不清楚，空调也应该快了，有一个公寓已经安上了，空气质量去年有一段时间确实非常非常差，可能是燃烧秸秆导致，别的大多数时候没什么不好的，洗浴是在校内的一个集中的澡堂，环境只能说还凑合，也不至于多不好，基本卫生没问题，不过很多时候我都去校外，虽然远点但也不麻烦，实验室确实明显破旧，不过器材好像不少都新的，做实验一点问题没有，厕所卫生除了宿舍之外都很干净，宿舍是一天一打扫，总是有神人不冲厕所没办法，不过一般也不至于没正常厕所上，这是我在东校的生活体验，有什么问题我看到了会再回复的，这就是个双非二本，虽然说生活条件没什么优势，但也不至于成为他的劣势，其他校区条件似乎是会差些，这个我不评价，我只说东校",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-05-03 07:58:29",
            "updated_at": "2026-05-03 07:58:29",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "d46c4b1e-6799-424e-bc6e-e04b8c0ac9f7",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 1,
            "reply_count": 1,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户5",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        },
        {
            "id": 2112,
            "user_id": 3275,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "此城市一个月有半个月中度污染及以上，空气质量及其差劲，北校每天早上七点多得出去跑操，晚上还有晚自习，宿舍楼堪比德军战俘营，宿舍厕所每天看了都只能说人类拉了一地，小便冲大便，澡堂子水都是偏黄的，还没有吹风机，拖鞋是从来不消毒的，一箱子拖鞋堪比生化武器，尤其理工科排课更是史中之史，每周四天早八三天满课，每周都有几天有莫名其妙活动占用为数不多的午休，强制学生参加某些无意义活动，教学楼实验器材比我岁数都大，都得是上个世纪的了，学校教室凳子桌子斑驳不堪不知道以为送到二战战场上经过炮火的洗礼了，最主要一栋楼上机课爬十一楼电梯就俩，每周都得上下一次十一楼，不知道以为搁这做有氧呢，这边也是给到拉完了",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-04-22 09:20:15",
            "updated_at": "2026-04-22 09:20:15",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "70ac8427-daa3-4366-a876-749807b00e55",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 1,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户3",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        },
        {
            "id": 6408,
            "user_id": 14318,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "来这上学真是当m了，早晚自习上个爽，周日晚上还要晚自习，开学前一天还要上晚自习。校区也就东校区能看些了，另外两个校区正是文物级别的了，学校宣传都不拍。这学校还挺要面子，学校的官方社交账号，比如抖音和微信公众号都不开评论区，真是怕被看见了什么。大一进来的时候有极小可能住4人寝，不然就8让上下床的小寝室，以后再想住4人寝的话就等大3大4抽签。4台电脑就跳闸，公厕臭的很，有时候去坑里面蹲出来，衣服都入味了，还有一堆神人拉了不冲，饮水机放厕所旁边，有时候有怪味",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-06-05 22:44:36",
            "updated_at": "2026-06-13 11:14:27",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "baca22f0-fd3b-4039-aeb1-6afa242972c5",
            "mod_suggestion": "block",
            "campus_id": 1131,
            "like_count": 0,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户8",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": "东校区",
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        },
        {
            "id": 5544,
            "user_id": 11706,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "纯纯的逆天学校，宿舍老破旧，6-8人寝室居多，还有十几人寝室，宿舍经常停水停电，北校区三公寓限电500w总共，晚上十一二点就男生宿舍全部断电，男女生宿舍待遇及其不均衡，女生宿舍起火或电压超载，转头就查男生宿舍，男女区别对待，留学生与本校生区别对待。东校区和北校区资源分配及其不均匀，有一点点水平的教师全部都在东校区，北校纯纯老破小，体育馆不给除了体育学院的任何学生使用，即使有体育学院的学生在羽毛球馆里滑板，都不给北校区非体育专业学生使用。你不能举报学校，因为一点点风吹草动都会招来学校的恶意处分。遇事先封口.黑人印度人都比本校学生过的好一万倍。北校区的塑胶跑道是烂了的，空气污染指数常年500居高不下，出去跑个步嗓子能辣死。学校附近全是工厂。",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-05-14 08:40:48",
            "updated_at": "2026-05-14 08:40:48",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "c26b8a60-c25b-44be-9383-78c8ee2fa1e3",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 0,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户7",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": {
                "id": 3685,
                "review_id": 5544,
                "dormitory": 1,
                "cafeteria": 3,
                "faculty": 2,
                "environment": 1,
                "culture": 3,
                "employment": 2,
                "safety": 4
            }
        },
        {
            "id": 5477,
            "user_id": 4057,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "首先，要声明的是北华大学师范分院和北华大学只有大层面的关系。即类似学信网这种国家的网站，在这里的人都可以是认证为北华大学，然后这里没有北华大学的宿舍，宿舍十人寝没有衣柜上下床，女寝充电宝充电有限制是两万瓦，男寝没有；其次，这里的老师分人，有的老师就很神经病，还有的老师以为自己很牛逼就会阴阳怪气你；还有，学校分为教一，教二和综合楼。25年各个楼刚取名字但是一般还是这么叫，综合楼是学校的门面，因为越近里面越破。学生会分系，有的学生会就像机器人一样只认死命令，当然不得不提到“节能减排”啦，也就是“学校寝室没电，教室里不让充电不让开窗不让开风扇”，最后如果来这学校的话，要么退学要么专升本，因为这学校不会卡你毕业",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-05-13 05:52:08",
            "updated_at": "2026-05-13 05:52:08",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "401eef83-bff4-40f9-8e67-e08ff2edcdf0",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 0,
            "reply_count": 0,
            "review_weight": 5,
            "is_question": 0,
            "nickname": "匿名用户6",
            "is_verified": 1,
            "verified_school_id": 457,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": true,
            "user_liked": false,
            "rating": {
                "id": 3627,
                "review_id": 5477,
                "dormitory": 1,
                "cafeteria": 4,
                "faculty": 4,
                "environment": 1,
                "culture": 2,
                "employment": 4,
                "safety": 3
            }
        },
        {
            "id": 2790,
            "user_id": 4673,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "寝室的话 我这边可能是中奖了，仅作参考吧，25 级大一新生心理学男生寝室是四人寝（南校2公寓），没有空调，限电特别严重。",
            "images": "/uploads/f08bdeef-2f0a-40c2-a620-9a80836ce270.jpg",
            "display_name": "匿名用户",
            "created_at": "2026-04-26 15:45:54",
            "updated_at": "2026-04-26 15:45:54",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "2cf6d0cf-7173-4c6c-b2e2-6d439f5323e1",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 0,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户4",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        },
        {
            "id": 1738,
            "user_id": 2702,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "早上六点整起床上早操 吃口饭就要开启一天的课程 晚自习还要上到晚上八点半 到宿舍看见八人寝连个桌子都没有天都塌了",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-04-21 11:28:58",
            "updated_at": "2026-04-21 11:28:58",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "61178421-faf6-4b3b-8d53-c8410627daf6",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 0,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户2",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": {
                "id": 818,
                "review_id": 1738,
                "dormitory": 1,
                "cafeteria": 1,
                "faculty": 2,
                "environment": 3,
                "culture": 1,
                "employment": null,
                "safety": 4
            }
        },
        {
            "id": 598,
            "user_id": 1082,
            "school_id": 457,
            "is_anonymous": 1,
            "status": "approved",
            "reject_reason": null,
            "content": "南校，校区老破小，宿舍八人没空调夏天是蒸笼，老师大多上课念ppt，基础设施极不完善，图书馆书全是和我一辈的，而且自习经常没座位，评价为烂完了😅😅😅",
            "images": null,
            "display_name": "匿名用户",
            "created_at": "2026-04-19 19:45:49",
            "updated_at": "2026-04-19 19:45:49",
            "view_count": 0,
            "submission_id": null,
            "mod_task_id": "a90be8e5-e193-417a-a0cb-75a0fd51da41",
            "mod_suggestion": "pass",
            "campus_id": null,
            "like_count": 0,
            "reply_count": 0,
            "review_weight": 0.08,
            "is_question": 0,
            "nickname": "匿名用户1",
            "is_verified": 0,
            "verified_school_id": null,
            "avatar_path": null,
            "level": null,
            "title": null,
            "campus_name": null,
            "isAnonymous": true,
            "isVerified": false,
            "user_liked": false,
            "rating": null
        }
    ]
}"#;
        let resp: ReviewResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.data[0].content, "此城市一个月有半个月中度污染及以上，空气质量及其差劲，北校每天早上七点多得出去跑操，晚上还有晚自习，宿舍楼堪比德军战俘营，宿舍厕所每天看了都只能说人类拉了一地，小便冲大便，澡堂子水都是偏黄的，还没有吹风机，拖鞋是从来不消毒的，一箱子拖鞋堪比生化武器，尤其理工科排课更是史中之史，每周四天早八三天满课，每周都有几天有莫名其妙活动占用为数不多的午休，强制学生参加某些无意义活动，教学楼实验器材比我岁数都大，都得是上个世纪的了，学校教室凳子桌子斑驳不堪不知道以为送到二战战场上经过炮火的洗礼了，最主要一栋楼上机课爬十一楼电梯就俩，每周都得上下一次十一楼，不知道以为搁这做有氧呢，这边也是给到拉完了".to_string());
    }
}
